---
- name: Update and clean DNF packages, notify and reboot if needed
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true

  tasks:
    # Get Installed Kernel Version before update
    - name: Get installed kernel version before update
      ansible.builtin.command: uname -r
      register: kernel_before
      changed_when: false

    # Remove unneeded packages
    - name: Remove unneeded packages
      ansible.builtin.dnf:
        autoremove: true
        state: absent

    # Upgrade all packages
    - name: Upgrade all packages with DNF
      ansible.builtin.dnf:
        update_cache: true
        name: '*'
        state: latest

    # Get Installed Kernel Version after update
    - name: Get installed kernel version after update
      ansible.builtin.command: uname -r
      register: kernel_after
      changed_when: false

    # Check if reboot is required
    - name: Check if system reboot is required
      become: true
      ansible.builtin.command: needs-restarting
      register: reboot_required
      changed_when: false

    # Set fact if reboot is required
    - name: Set fact if reboot is required
      ansible.builtin.set_fact:
        reboot_is_required: true
      when: reboot_required = true or kernel_before.stdout != kernel_after.stdout

    # Send Discord message when reboot is required
    - name: Send Discord message
      ansible.builtin.uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body: '{"content": "Rebooting {{ ansible_hostname }} {{ ansible_default_ipv4.address }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_is_required | default(false) | bool

    # Rebooting
    - name: Rebooting Systems
      become: true
      ansible.builtin.reboot:
        msg: "Rebooting due to package updates"
      when: reboot_is_required | default(false) | bool
