- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true

  tasks:
    # Install dnf-utils if not already installed (needed for needs-restarting)
    - name: Install dnf-utils
      dnf:
        name: 
        - dnf-utils
        state: present
      when: "'dnf-utils' not in ansible_facts.packages"

    # Remove unneeded packages
    - name: Remove unneeded packages
      dnf:
        autoremove: true
        state: absent

    # Upgrade all packages
    - name: Upgrade all packages with DNF
      dnf:
        update_cache: true
        name: '*'
        state: latest

    # Check if reboot is required
    - name: Check if system reboot is required
      command: needs-restarting -r
      register: reboot_required
      failed_when: reboot_required.rc not in [0, 1]
      changed_when: reboot_required.rc == 1
      when: ansible_facts['os_family'] == 'RedHat'

    # Send Discord message when reboot is required
    - name: Send Discord message
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body: '{"content": "Rebooting {{ inventory_hostname }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      # Send the Discord message only if a reboot is required
      when: reboot_required.rc == 1

    # Rebooting
    - name: Rebooting Systems
      reboot:
        msg: "Rebooting due to package updates"
      when: reboot_required.rc == 1
