---
- name: Update and clean DNF packages, notify and reboot if needed
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # Remove unneeded packages
    - name: Remove unneeded packages
      become: true
      ansible.builtin.dnf:
        autoremove: true
        state: absent

    # Upgrade all packages
    - name: Upgrade all packages with DNF
      become: true
      ansible.builtin.dnf:
        update_cache: true
        name: '*'
        state: latest

    # Check if reboot is required
    - name: Check if reboot is required
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: false

    # Set fact if reboot is required
    - name: Set fact if reboot is required
      ansible.builtin.set_fact:
        reboot_is_required: true
      when: reboot_required.rc == 1

    # Send Discord message when reboot is required
    - name: Send Discord message
      ansible.builtin.uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body: '{"content": "Rebooting {{ ansible_hostname }} {{ ansible_default_ipv4.address }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_is_required | default(false) | bool

    # Rebooting
    - name: Reboot system if required
      become: true
      ansible.builtin.reboot:
        msg: "Rebooting due to package updates"
      when: reboot_is_required | default(false) | bool
