---
- name: Check for available updates on AlmaLinux
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get list of available updates
      command: dnf list updates --quiet
      register: dnf_updates
      changed_when: false
      failed_when: false

    - name: Parse update list
      set_fact:
        available_updates: "{{ dnf_updates.stdout_lines | select('search', '^[a-zA-Z0-9]') | list }}"

    - name: Identify Kernel updates
      set_fact:
        kernel_updates: "{{ available_updates | select('search', 'kernel') | list }}"

    - name: Send Discord message if kernel updates are available
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            🚀 Kernel updates available on **{{ inventory_hostname }}**:
            {{ kernel_updates | join('\n') }}
        headers:
          Content-Type: application/json
        status_code: 204
      when: kernel_updates | length > 0

    - name: Send Discord message if general updates are available
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            📌 Updates available on **{{ inventory_hostname }}**:
            {{ available_updates | join('\n') }}
        headers:
          Content-Type: application/json
        status_code: 204
      when: available_updates | length > 0 and kernel_updates | length == 0
