# .ansible-lint.yaml
skip_list:
  - package-latest  # Ignoriert den Fehler für "state: latest" in Paketen

allow_list:
  syntax-check:
    - community.docker.docker_prune  # Erlaubt spezifisch das Docker-Prune-Modul
