---
- name: Fail if not a Debian-based system
  ansible.builtin.fail:
    msg: "This role only supports Debian-family systems"
  when: ansible_facts['distribution'] not in ['Debian', 'Ubuntu']

- name: Upgrade Apt Packages
  become: true
  ansible.builtin.apt:
    autoclean: true
    update_cache: true
    autoremove: true
    upgrade: 'dist'

- name: Check If System Reboot Is Required
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Send Discord Message about reboot
  ansible.builtin.uri:
    url: '{{ webhook_url }}'
    method: POST
    body_format: json
    body: '{"content": "Rebooting {{ inventory_hostname }} after updates"}'
    headers:
      Content-Type: application/json
    status_code: 204
  when: reboot_required.stat.exists

- name: Reboot system if required
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting due to package updates"
  when: reboot_required.stat.exists
