---
- name: Extract kernel version
  ansible.builtin.set_fact:
    current_kernel: "{{ ansible_facts.kernel.split('-')[0:2] | join('-') }}"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Filter installed kernel packages
  ansible.builtin.set_fact:
    filtered_kernels: >-
      {{ ansible_facts.packages.keys()
        | select('match', '^linux-image-[0-9].*')
        | reject('search', current_kernel)
        | reject('equalto', 'linux-image-amd64')
        | sort
        | list }}

- name: Get list of kernels to remove (all but last 2)
  ansible.builtin.set_fact:
    kernels_to_remove: "{{ filtered_kernels[0 : (filtered_kernels | length - 2)] if filtered_kernels | length > 2 else [] }}"

- name: Remove old kernels
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop: "{{ kernels_to_remove }}"
  when: kernels_to_remove | length > 0

- name: Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
