---
galaxy_info:
  author: Ali333n
  description: Keepalived VIP for redundant HAProxy nodes
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
