---
- name: Full Debian maintenance with disk space check, updates and kernel cleanup
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: true

  roles:
    - role: maintenance
