---
- name: Check for Updates and Notify via Discord
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: yes

  tasks:
    - name: Refresh package cache
      become: yes
      apt:
        update_cache: true

    - name: Check for available updates
      become: yes
      shell: apt list --upgradable 2>/dev/null | grep -v "Listing..."
      register: available_updates
      changed_when: false
      failed_when: false

    - name: Send Discord notification if updates are available
      when: available_updates.stdout_lines | length > 0
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            Updates are available on {{ inventory_hostname }}:
            {{ available_updates.stdout_lines | join('\n') }}
        headers:
          Content-Type: application/json
        status_code: 204
