---
- name: Check for Updates and Notify via Discord
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: yes

  tasks:
    - name: Update package cache and check for available updates
      become: yes
      apt:
        update_cache: true
      register: apt_cache_update

    - name: List available updates
      become: yes
      apt:
        update_cache: no
        upgrade: safe
        dry_run: true
      register: apt_updates
      changed_when: false

    - name: Send Discord notification if updates are available
      when: apt_updates.changes.packages | length > 0
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            Updates are available on {{ inventory_hostname }}:
            {{ apt_updates.changes.packages | list | join(', ') }}
        headers:
          Content-Type: application/json
        status_code: 204
