---
- name: Check for Updates and Notify via Discord
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: yes

  tasks:
    - name: Check for available updates using Ansible apt module
      become: yes
      apt:
        update_cache: true
        upgrade: list
      register: apt_updates

    - name: Send Discord notification if updates are available
      when: apt_updates.upgradeable_packages | length > 0
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            Updates are available on {{ inventory_hostname }}:
            {{ apt_updates.upgradeable_packages | map(attribute='package') | join(', ') }}
        headers:
          Content-Type: application/json
        status_code: 204
