- name: Update and Reboot Debian Systems
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: true

  tasks:
    # Upgrade packages
    - name: Upgrade Apt Packages
      become: true
      ansible.builtin.apt:
        autoclean: true
        update_cache: true
        autoremove: true
        upgrade: dist

    # Check if reboot is required
    - name: Check If System Reboot Is Required
      become: true
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Send Discord message when reboot is required
    - name: Send Discord Message
      ansible.builtin.uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body: '{"content": "Rebooting {{ inventory_hostname }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists

    # Rebooting
    - name: Rebooting Systems
      become: true
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
