---
- name: Check for Updates and Notify via Discord
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: yes

  tasks:
    - name: Cache aktualisieren
      apt:
        update_cache: true
      become: yes

    - name: Verfügbare Updates simulieren
      shell: "LC_ALL=C apt-get -s -o Debug::NoLocking=true dist-upgrade"
      register: apt_sim
      changed_when: false
      become: yes

    - name: Anzahl upgradebarer Pakete ermitteln
      set_fact:
        upgrades_available: "{{ (apt_sim.stdout | regex_findall('^Inst') | length) | int }}"

    - name: Send Discord notification if updates are available
      when: upgrades_available | int > 0
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            Updates are available on {{ inventory_hostname }}:
            Total packages: {{ upgrades_available }}
        headers:
          Content-Type: application/json
        status_code: 204
