- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: true

  tasks:
    # Test if python3-apt is installed
    - name: Show Python interpreter
      debug:
        msg: "Interpreter: {{ ansible_python_interpreter }}"

    - name: Test python3-apt import
      raw: /usr/bin/python3 -c "import apt; print('python3-apt OK')"
      register: apt_import_test
      ignore_errors: yes

    - name: Show python3-apt check
      debug:
        var: apt_import_test.stdout

    # Upgrade packages
    - name: upgrade apt packages
      become: true
      ansible.builtin.apt:
        autoclean: true
        update_cache: true
        autoremove: true
        upgrade: dist

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Send Discord message when reboot is required
    - name: Send Discord message
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body: '{"content": "Rebooting {{ inventory_hostname }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists

    # Rebooting
    - name: Rebooting Systems
      reboot:
      when: reboot_required.stat.exists == true