---
all:
  children:
    mariadb_cluster:
      hosts:
        db01:
          ansible_host: 10.10.20.11
        db02:
          ansible_host: 10.10.20.12
        db03:
          ansible_host: 10.10.20.13

    loadbalancer:
      hosts:
        lb01:
          ansible_host: 10.10.20.20
        lb02:
          ansible_host: 10.10.20.21
