---
all:
  children:
    mariadb_cluster:
      hosts:
        db01:
          ansible_host: 10.0.50.41
        db02:
          ansible_host: 10.0.50.42
        db03:
          ansible_host: 10.0.50.43

    loadbalancer:
      hosts:
        lb01:
          ansible_host: 10.0.50.31
        lb02:
          ansible_host: 10.0.50.32
