---
galaxy_info:
  author: Ali333n
  description: MariaDB Galera cluster node
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
