---
- name: Clean docker
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true

  tasks:
    - name: Prune non-dangling images
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: false
        volumes: false
        builder_cache: false
