---
- name: Check for Updates
  hosts: all
  gather_facts: yes

  tasks:
    - name: Run apt-get update command
      become: yes
      shell: apt update

    - name: Check for available updates
      become: yes
      shell: apt list --upgradable | grep -v "Listing..."
      register: available_updates
      ignore_errors: true

    - name: Send Discord notification with available updates
      when: available_updates.stdout_lines | length > 0
      uri:
        url: '{{ webhook_url }}'
        method: POST
        body_format: json
        body:
          content: |
            Updates are available on {{ inventory_hostname }}:
            {{ available_updates.stdout }}
        headers:
          Content-Type: application/json
        status_code: 204
