name: Ansible Lint

on:
  push:
    paths:
      - 'Playbooks/**'
  pull_request:
    paths:
      - 'Playbooks/**'

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install latest Ansible Lint
        run: pip install --upgrade ansible-lint

      - name: Run Ansible Lint
        uses: ansible/ansible-lint@main
        with:
          args: '-p Playbooks -x var-naming[no-role-prefix]'
          setup_python: "false"
          working_directory: ""
