name: Ansible files & Deployment 

on:
  push:
    paths:
      - 'Playbooks/**'
  pull_request:
    paths:
      - 'Playbooks/**'

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p Playbooks -x var-naming[no-role-prefix]'
